<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <ProjectReference Include="..\IracingSetupManager.Core\IracingSetupManager.Core.csproj" />
  </ItemGroup>
</Project>
